//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Services {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.IEchoClaims")]
    public interface IEchoClaims {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEchoClaims/Echo", ReplyAction="http://tempuri.org/IEchoClaims/EchoResponse")]
        string Echo();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEchoClaimsChannel : UI.Services.IEchoClaims, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EchoClaimsClient : System.ServiceModel.ClientBase<UI.Services.IEchoClaims>, UI.Services.IEchoClaims {
        
        public EchoClaimsClient() {
        }
        
        public EchoClaimsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EchoClaimsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EchoClaimsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EchoClaimsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Echo() {
            return base.Channel.Echo();
        }
    }
}
